/**
 * This code was generated by Builder.io.
 */
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: ["b.io"],
  },
};

module.exports = nextConfig;
