name: Build and Push Docker Image

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Build Docker image
              run:
                  docker-compose -f docker-compose.yml build

            - name: Start Docker Compose services
              run:
                  docker-compose -f docker-compose.yml up -d

            - name: Run tests
              run:
                  echo "Running tests..."
                  
            - name:
              run:
                  docker-compose -f docker-compose.yml down
