name: CI

on:
  push:
    branches:
      – main
  pull_request:
    branches:
      – main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      – name: Checkout repository
        uses: actions/checkout@v2

      – name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build 

      – name: Start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

      – name: Run tests
        run: |
          echo "Running tests..."
          echo "There are no tests :)"

      – name: Stop and remove Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down
